version: "3.9"
services:
#  postgres:
#    image: postgres:15
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: marketplace
#    ports:
#      - "5432:5432"
  product-service:
    build:
      context: .
    env_file:
      - .env.example
    depends_on:
      - postgres
    ports:
      - "8080:8080"